name: insightmate
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  text_to_speech: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
